#my.greetings = Hello from property file
#list values
My:
  list:
    values : 1,2,3
#keyvalue pairs
DbValues : "{ConnectionString: 'https://mongodb.com', UserName:'Gohul', Password:'pass'}"
#Advantage of yml file, we can be able to nesting the values.
db:
  connection : "{ connectionString: 'http://mongodb.com-test', userName:'gohul', password: 'pass'}"
  host : 123.41.11.11
  port : 1212

app:
  name : My App
  description : welcome to ${app.name}

management.endpoints.web.exposure.include: "*"


